cmake_minimum_required(VERSION 3.15)

find_package(boost_any REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_detail REQUIRED CONFIG)
find_package(boost_function REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_lexical_cast REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_bind REQUIRED CONFIG)
find_package(boost_tokenizer REQUIRED CONFIG)
