cmake_minimum_required(VERSION 3.15)

find_package(boost_asio REQUIRED CONFIG)
find_package(boost_callable_traits REQUIRED CONFIG)
find_package(boost_circular_buffer REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_intrusive REQUIRED CONFIG)
find_package(boost_leaf REQUIRED CONFIG)
find_package(boost_mp11 REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_system REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_variant2 REQUIRED CONFIG)

if (BOOST_COBALT_USE_BOOST_CONTAINER)
    find_package(boost_container REQUIRED CONFIG)
endif()
