cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_array REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_detail REQUIRED CONFIG)
find_package(boost_integer REQUIRED CONFIG)
find_package(boost_io REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_move REQUIRED CONFIG)
find_package(boost_mpl REQUIRED CONFIG)
find_package(boost_optional REQUIRED CONFIG)
find_package(boost_predef REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_spirit REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_unordered REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
find_package(boost_variant REQUIRED CONFIG)
find_package(boost_function REQUIRED CONFIG)