cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_dynamic_bitset REQUIRED CONFIG)
find_package(boost_integer REQUIRED CONFIG)
find_package(boost_io REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_system REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
find_package(boost_array REQUIRED CONFIG)
find_package(boost_range REQUIRED CONFIG)
