cmake_minimum_required(VERSION 3.15)

find_package(boost_headers REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_container_hash REQUIRED CONFIG)
find_package(boost_detail REQUIRED CONFIG)
find_package(boost_io REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_system REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_atomic REQUIRED CONFIG)
find_package(boost_predef REQUIRED CONFIG)
find_package(boost_scope REQUIRED CONFIG)
if (WIN32)
  find_package(boost_winapi REQUIRED CONFIG)
endif()
