cmake_minimum_required(VERSION 3.15)

find_package(boost_headers REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_algorithm REQUIRED CONFIG)
find_package(boost_asio REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_fusion REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_move REQUIRED CONFIG)
find_package(boost_optional REQUIRED CONFIG)
find_package(boost_system REQUIRED CONFIG)
find_package(boost_tokenizer REQUIRED CONFIG)
find_package(boost_type_index REQUIRED CONFIG)
find_package(boost_winapi REQUIRED CONFIG)
if (NOT BOOST_PROCESS_USE_STD_FS)
    find_package(boost_filesystem REQUIRED CONFIG)
endif()
