cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_atomic REQUIRED CONFIG)
find_package(boost_bind REQUIRED CONFIG)
find_package(boost_chrono REQUIRED CONFIG)
find_package(boost_concept_check REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_container REQUIRED CONFIG)
find_package(boost_container_hash REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_date_time REQUIRED CONFIG)
find_package(boost_exception REQUIRED CONFIG)
find_package(boost_function REQUIRED CONFIG)
find_package(boost_io REQUIRED CONFIG)
find_package(boost_move REQUIRED CONFIG)
find_package(boost_optional REQUIRED CONFIG)
find_package(boost_predef REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_system REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_tuple REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
find_package(boost_winapi REQUIRED CONFIG)
