cmake_minimum_required(VERSION 3.15)

find_package(boost_algorithm REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_io REQUIRED CONFIG)
find_package(boost_lexical_cast REQUIRED CONFIG)
find_package(boost_numeric_conversion REQUIRED CONFIG)
find_package(boost_range REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_tokenizer REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
find_package(boost_winapi REQUIRED CONFIG)
