cmake_minimum_required(VERSION 3.15)

find_package(boost_headers REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_fusion REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_mp11 REQUIRED CONFIG)
find_package(boost_mpl REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_typeof REQUIRED CONFIG)
find_package(boost_vmd REQUIRED CONFIG)
find_package(boost_thread REQUIRED CONFIG)