cmake_minimum_required(VERSION 3.15)

find_package(boost_assert REQUIRED CONFIG)
find_package(boost_config REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_detail REQUIRED CONFIG)
find_package(boost_function REQUIRED CONFIG)
find_package(boost_integer REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_mpl REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_random REQUIRED CONFIG)
find_package(boost_range REQUIRED CONFIG)
find_package(boost_regex REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
find_package(boost_numeric_conversion REQUIRED CONFIG)

find_package(ZLIB CONFIG)
find_package(BZip2 CONFIG)
find_package(zstd CONFIG)
find_package(LibLZMA CONFIG)
