cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_headers REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_foreach REQUIRED CONFIG)
find_package(boost_function REQUIRED CONFIG)
find_package(boost_graph REQUIRED CONFIG)
find_package(boost_integer REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_mpl REQUIRED CONFIG)
find_package(boost_optional REQUIRED CONFIG)
find_package(boost_serialization REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
find_package(boost_lexical_cast REQUIRED CONFIG)
find_package(boost_utility REQUIRED CONFIG)
