cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_concept_check REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_filesystem REQUIRED CONFIG)
find_package(boost_format REQUIRED CONFIG)
find_package(boost_iterator REQUIRED CONFIG)
find_package(boost_lexical_cast REQUIRED CONFIG)
find_package(boost_mpl REQUIRED CONFIG)
find_package(boost_multi_index REQUIRED CONFIG)
find_package(boost_optional REQUIRED CONFIG)
find_package(boost_pool REQUIRED CONFIG)
find_package(boost_preprocessor REQUIRED CONFIG)
find_package(boost_serialization REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_spirit REQUIRED CONFIG)
find_package(boost_static_assert REQUIRED CONFIG)
find_package(boost_throw_exception REQUIRED CONFIG)
find_package(boost_type_traits REQUIRED CONFIG)
