cmake_minimum_required(VERSION 3.15)

find_package(boost_config REQUIRED CONFIG)
find_package(boost_assert REQUIRED CONFIG)
find_package(boost_context REQUIRED CONFIG)
find_package(boost_core REQUIRED CONFIG)
find_package(boost_intrusive REQUIRED CONFIG)
find_package(boost_predef REQUIRED CONFIG)
find_package(boost_smart_ptr REQUIRED CONFIG)
find_package(boost_algorithm REQUIRED CONFIG)
find_package(boost_filesystem REQUIRED CONFIG)
find_package(boost_format REQUIRED CONFIG)
