name: Build Boost Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BOOST_VERSION: 1.87.0

jobs:
  build-boost:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ensure cache directory exists
        run: mkdir -p cache

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: cache/
          key: ${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ hashFiles('cache/*.tgz') }}

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect -f

      - name: Restore Conan cache
        if: ${{ steps.check_cache.outputs.exists == 'true' }}
        run: conan cache restore cache/${{ runner.os }}_conan_cache_save.tgz

      - name: Build Boost packages
        run: python build_boost.py

      - name: Backup Conan cache
        run: conan cache save "*/*:*" --file cache/${{ runner.os }}_conan_cache_save.tgz
