name: Build Boost Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BOOST_VERSION: 1.87.0

jobs:
  build-boost:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect

      - name: Build Boost packages
        run: python build.py

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
            C:\Users\runneradmin\.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.py', '**/conandata.yml.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-