name: Build Boost Libraries on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BOOST_VERSION: 1.87.0

jobs:
  build-boost:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect

      - name: Export Boost packages
        run: |
          set -ex
          for folder in $(find ${GITHUB_WORKSPACE} -maxdepth 1 -type d -name "boost-*"); do
            echo "Exporting $folder"
            conan export $folder/all --version=${{ env.BOOST_VERSION }}
          done

      - name: Build Boost packages
        run: |
          set -ex
          for folder in $(find ${GITHUB_WORKSPACE} -maxdepth 1 -type d -name "boost-*"); do
            echo "Building $folder"
            conan create $folder/all --version=${{ env.BOOST_VERSION }} --build=missing
          done

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-boost-${{ env.BOOST_VERSION }}
          restore-keys: |
            ${{ runner.os }}-conan-boost-
