name: Build Boost Libraries on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BOOST_VERSION: 1.87.0

jobs:
  build-boost:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect

      - name: Export Boost packages
        run: |
          set -ex
          for /d %%F in (boost-*) do (
            echo Exporting %%F
            conan export %%F\all --version=${{ env.BOOST_VERSION }}
          )

      - name: Build Boost packages
        run: |
          set -ex
          for /d %%F in (boost-*) do (
            echo Building %%F
            conan create %%F\all --version=${{ env.BOOST_VERSION }} --build=missing
          )

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: "%USERPROFILE%/.conan2"
          key: ${{ runner.os }}-conan-boost-${{ env.BOOST_VERSION }}
          restore-keys: |
            ${{ runner.os }}-conan-boost-